import { AdVariant } from './AdVariantCard';

export const adVariantsByRegion: Record<string, AdVariant[]> = {
  'kenya': [
    {
      id: 'ke-1',
      name: 'Safari Vibes',
      headline: 'Elevate Your Game, Mzalendo! 🔥',
      body: "Sasa! Ready to level up your hustle? Our AI-powered platform is built for the Kenyan entrepreneur who's ready to make moves. Karibu to the future of business – designed with Kenyan innovation in mind.",
      cta: 'Twende Mbele!',
      tone: 'Bold & Local',
    },
    {
      id: 'ke-2',
      name: 'Professional Edge',
      headline: 'Transform Your Brand with AI Excellence',
      body: "Join leading Kenyan businesses leveraging cutting-edge AI technology. From Nairobi to Mombasa, we're helping entrepreneurs across the country build world-class brands that compete globally.",
      cta: 'Start Your Journey',
      tone: 'Professional',
    },
    {
      id: 'ke-3',
      name: 'Community Focus',
      headline: 'Built for Kenya, Made for Success',
      body: "Tuko pamoja! Whether you're running a startup in Westlands or scaling your business in Kisumu, our platform understands the unique challenges and opportunities of the Kenyan market.",
      cta: 'Join the Movement',
      tone: 'Community',
    },
  ],
  'south-africa': [
    {
      id: 'za-1',
      name: 'Rainbow Nation',
      headline: 'Lekker Tech for Lekker Brands! 🇿🇦',
      body: "Howzit! Ready to take your business to the next level? Our AI platform is proudly built to help South African entrepreneurs create world-class campaigns. From Joburg to Cape Town, we've got you covered.",
      cta: 'Get Started, Boet!',
      tone: 'Authentic SA',
    },
    {
      id: 'za-2',
      name: 'Enterprise Ready',
      headline: 'AI-Powered Marketing for African Excellence',
      body: "South African businesses are making their mark on the global stage. Our platform combines international best practices with local market intelligence to help you stand out in an increasingly competitive landscape.",
      cta: 'Elevate Your Brand',
      tone: 'Corporate',
    },
    {
      id: 'za-3',
      name: 'Startup Spirit',
      headline: 'Sharp Sharp! Your AI Marketing Partner',
      body: "From Soweto startups to Sandton enterprises, we're helping SA brands tell their stories with the power of AI. No more struggling with content – let's make your brand shine like the African sun.",
      cta: 'Let\'s Do This',
      tone: 'Energetic',
    },
  ],
  'us': [
    {
      id: 'us-1',
      name: 'Silicon Valley',
      headline: 'AI Marketing That Actually Delivers 🚀',
      body: "Tired of marketing tools that overpromise and underdeliver? Our AI platform cuts through the noise to generate campaigns that convert. Real results, real fast – built by founders, for founders.",
      cta: 'Start Free Trial',
      tone: 'Direct',
    },
    {
      id: 'us-2',
      name: 'Heartland Appeal',
      headline: 'Smart Marketing for American Businesses',
      body: "From Main Street to Wall Street, American businesses trust our AI to create compelling campaigns. Simple, effective, and built to help you compete in today's fast-moving market.",
      cta: 'Get Started Today',
      tone: 'Trustworthy',
    },
    {
      id: 'us-3',
      name: 'Gen-Z Focus',
      headline: 'Your Brand\'s Main Character Era Starts Here ✨',
      body: "No cap – our AI creates content that hits different. Whether you're building a personal brand or scaling your startup, we help you create campaigns that actually resonate with your audience. It's giving success.",
      cta: 'Slay Your Marketing',
      tone: 'Trendy',
    },
  ],
  'uk': [
    {
      id: 'uk-1',
      name: 'British Sophistication',
      headline: 'Brilliant AI Marketing, Full Stop.',
      body: "Straightforward, effective, and undeniably clever – our AI platform helps British businesses create campaigns that resonate. No faff, no fuss, just proper marketing that delivers results.",
      cta: 'Get Started',
      tone: 'Refined',
    },
    {
      id: 'uk-2',
      name: 'London Startup',
      headline: 'AI Marketing That\'s Absolutely Mint 🎯',
      body: "Whether you're in Shoreditch or Sheffield, our platform helps you create campaigns that are bang on. Built for the UK market, designed to help your brand absolutely smash it.",
      cta: 'Crack On',
      tone: 'Casual British',
    },
    {
      id: 'uk-3',
      name: 'Enterprise UK',
      headline: 'Elevate Your Brand with AI Excellence',
      body: "Britain's leading businesses trust our AI platform to deliver exceptional marketing campaigns. Combining cutting-edge technology with market intelligence, we help you maintain your competitive edge.",
      cta: 'Book a Demo',
      tone: 'Corporate',
    },
  ],
  'middle-east': [
    {
      id: 'me-1',
      name: 'Dubai Luxury',
      headline: 'Experience Premium AI Marketing ✨',
      body: "Welcome to the future of brand excellence. Our AI platform delivers the sophistication and quality that Middle Eastern businesses demand. From Dubai to Riyadh, we create campaigns worthy of your ambition.",
      cta: 'Discover Excellence',
      tone: 'Luxurious',
    },
    {
      id: 'me-2',
      name: 'Regional Innovation',
      headline: 'AI Marketing for the New Middle East',
      body: "The region is transforming, and your marketing should too. Our platform combines global AI technology with deep understanding of local markets, helping you connect authentically across the GCC and beyond.",
      cta: 'Start Your Journey',
      tone: 'Visionary',
    },
    {
      id: 'me-3',
      name: 'Arabic Blend',
      headline: 'Yalla! Transform Your Brand with AI 🌟',
      body: "Habibi, your brand deserves the best! From Abu Dhabi's innovation hubs to Jeddah's bustling markets, our AI understands the nuances that make Middle Eastern audiences tick. Let's create something extraordinary together.",
      cta: 'Join Us Today',
      tone: 'Friendly',
    },
  ],
  'australia': [
    {
      id: 'au-1',
      name: 'Down Under Direct',
      headline: 'No Worries, Mate – AI Marketing Made Easy 🦘',
      body: "G'day! Ready to give your marketing a fair dinkum upgrade? Our AI platform helps Aussie businesses create ripper campaigns without the hassle. From Sydney to Perth, we've got your back.",
      cta: 'Give It a Go',
      tone: 'Laid-back',
    },
    {
      id: 'au-2',
      name: 'Business Australia',
      headline: 'Smart AI Marketing for Australian Businesses',
      body: "Australian businesses are known for punching above their weight, and your marketing should too. Our platform delivers enterprise-grade AI campaigns tailored for the Australian market.",
      cta: 'Start Your Trial',
      tone: 'Professional',
    },
    {
      id: 'au-3',
      name: 'Startup Scene',
      headline: 'Your Secret Weapon for Brand Growth 🚀',
      body: "The Aussie startup scene is firing on all cylinders, and our AI platform is here to fuel your growth. Create campaigns that cut through, engage your audience, and drive real results. Too easy!",
      cta: 'Let\'s Get Started',
      tone: 'Energetic',
    },
  ],
  'malaysia': [
    {
      id: 'my-1',
      name: 'Malaysian Fusion',
      headline: 'AI Marketing with Malaysian Heart 🇲🇾',
      body: "Apa khabar! From KL's skyscrapers to Penang's heritage streets, our AI understands the diverse Malaysian market. Create campaigns that resonate across all communities – Boleh!",
      cta: 'Cuba Sekarang',
      tone: 'Local Blend',
    },
    {
      id: 'my-2',
      name: 'Tech Forward',
      headline: 'Powering Malaysia\'s Digital Future',
      body: "Malaysia is rapidly becoming a digital powerhouse, and your brand should lead the charge. Our AI platform helps Malaysian businesses compete globally while staying true to local values.",
      cta: 'Get Started Today',
      tone: 'Modern',
    },
    {
      id: 'my-3',
      name: 'SME Champion',
      headline: 'Best Lah! AI Marketing for Every Business',
      body: "Wah, marketing can be susah, but not anymore! Whether you're running a kedai in Melaka or a tech startup in Cyberjaya, our AI makes professional marketing accessible to everyone.",
      cta: 'Jom Try!',
      tone: 'Friendly Local',
    },
  ],
  'canada': [
    {
      id: 'ca-1',
      name: 'True North',
      headline: 'AI Marketing, Eh? Absolutely! 🍁',
      body: "From coast to coast to coast, Canadian businesses trust our AI platform to create campaigns that resonate with our unique market. Inclusive, innovative, and incredibly effective – just like Canada.",
      cta: 'Get Started',
      tone: 'Friendly Canadian',
    },
    {
      id: 'ca-2',
      name: 'Bilingual Bridge',
      headline: 'Marketing Excellence from Sea to Sea',
      body: "Canada's diversity is our strength, and our AI understands that. Create campaigns that connect with audiences from Vancouver to Montreal, Toronto to Halifax – in English and French.",
      cta: 'Try It Free',
      tone: 'Inclusive',
    },
    {
      id: 'ca-3',
      name: 'Startup North',
      headline: 'Power Your Startup with Canadian AI 🚀',
      body: "The Canadian tech scene is booming, and our AI platform is here to help you stand out. Whether you're in Waterloo's tech triangle or Vancouver's startup hub, we help you compete globally.",
      cta: 'Launch Your Campaign',
      tone: 'Ambitious',
    },
  ],
};
